# https://github.com/monarin/psana-nersc/blob/master/demo19/Dockerfile
# *NOTE*
# - The ENV _proxy lines are specific for building this docker image at SLAC.
# - For lcls2 and cctbx repos, you can use git clone: e.g.
#   -- replace ADD lcls2 lcls2 with RUN git clone https://github.com/slac-lcls/lcls2.git
#   -- replace all the cctbx build lines with
#      RUN mkdir cctbx &&\
#          cd cctbx &&\
#          wget https://raw.githubusercontent.com/cctbx/cctbx_project/master/libtbx/auto_build/bootstrap.py &&\
#          python bootstrap.py hot update build --builder=dials --with-python=/opt/conda/bin/python --nproc=8 &&\
#          cd ..
FROM centos:centos7

#ENV http_proxy http://psproxy:3128
#ENV https_proxy https://psproxy:3128
#ENV ftp_proxy $http_proxy

RUN yum clean all && \
    yum -y update && \
    yum -y install centos-release-scl-rh && \
    yum -y install devtoolset-7-gcc devtoolset-7-gcc-c++ devtoolset-7-gcc-gfortran \
                   devtoolset-7-make wget bzip2 strace && \
    yum clean all -y

RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
    chmod +x /root/Miniconda3-latest-Linux-x86_64.sh && \
    /root/Miniconda3-latest-Linux-x86_64.sh -b -p /opt/anaconda && \
    rm /root/Miniconda3-latest-Linux-x86_64.sh &&
    echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
    echo "conda activate base" >> ~/.bashrc && \
    echo "source /opt/rh/devtoolset-7/enable" >> ~/.bashrc && \
    source ~/.bashrc && \
    conda update -y conda && \
    conda update -y --all && \
    conda install -y git "mpich>=7" mpi4py python=3.10 cmake numpy cython matplotlib pytest mongodb pymongo curl rapidjson ipython requests mypy h5py -c defaults -c anaconda -c conda-forge && \
    conda install -y amityping -c lcls-ii && \
    conda clean -y --all

RUN echo "backend : AGG" > /tmp/matplotlibrc
ENV MATPLOTLIBRC=/tmp/matplotlibrc

SHELL ["/bin/bash", "-c"]
ENV BASH_ENV ~/.bashrc

#ADD lcls2 lcls2

WORKDIR /home/psana2-build
RUN git clone https://github.com/apeck12/lcls2.git && \
    cd lcls2 && \
    . /opt/anaconda/etc/profile.d/conda.sh && \
    source ~/.bashrc && \
    export PATH=/home/psana2-build/lcls2/install/bin:$PATH && \
    export PYTHONPATH=/home/psana2-build/lcls2/install/lib/python3.10/site-packages && \
    export TESTRELDIR=/home/psana2-build/lcls2/install && \
    export MANPATH=$CONDA_PREFIX/share/man${MANPATH:+:${MANPATH}} && \
    ./build_all.sh
#RUN pushd lcls2 && \
#    PYTHONPATH=/lcls2/install/lib/python3.6/site-packages ./build_all.sh -d && \
#    popd

RUN conda uninstall --force mpich

## build cctbx
##ADD cctbx cctbx
##RUN cd cctbx &&\
##    python bootstrap.py build --builder=dials --with-python=/opt/conda/bin/python --nproc=8 &&\
##    cd ..
#
#
## setup environments for psana2 and cctbx
ENV CONDA_EXE=/opt/conda/bin/conda
ENV CONDA_PREFIX=/opt/conda
ENV CONDA_PROMPT_MODIFIER=(base)
ENV CONDA_PYTHON_EXE=/opt/conda/bin/python
ENV CONDA_SHLVL=1
ENV INFOPATH=/opt/rh/devtoolset-7/root/usr/share/info

ENV LD_LIBRARY_PATH=/opt/udiImage/modules/mpich/lib64:/opt/rh/devtoolset-7/root/usr/lib64:/opt/rh/devtoolset-7/root/usr/lib:/opt/rh/devtoolset-7/root/usr/lib64/dyninst:/opt/rh/devtoolset-7/root/usr/lib/dyninst:/opt/rh/devtoolset-7/root/usr/lib64:/opt/rh/devtoolset-7/root/usr/lib
#ENV MANPATH=/opt/rh/devtoolset-7/root/usr/share/man:/usr/common/software/man:/usr/common/mss/man:/usr/common/nsg/man:/opt/cray/pe/mpt/7.7.0/gni/man/mpich:/opt/cray/pe/atp/2.1.1/man:/opt/cray/alps/6.5.28-6.0.5.0_18.6__g13a91b6.ari/man:/opt/cray/job/2.2.2-6.0.5.0_8.47__g3c644b5.ari/man:/opt/cray/pe/pmi/5.0.13/man:/opt/cray/pe/libsci/18.03.1/man:/opt/cray/pe/man/csmlversion:/opt/cray/pe/craype/2.5.14/man:/opt/intel/compilers_and_libraries_2018.1.163/linux/man/common:/usr/syscom/nsg/man:/opt/cray/pe/modules/3.2.10.6/share/man:/global/homes/c/canon/man:/usr/local/man:/usr/share/man:/opt/cray/share/man:/opt/cray/pe/man:/opt/cray/share/man
ENV PATH=/lcls2/install/bin:/lcls2/build/bin:/opt/rh/devtoolset-7/root/usr/bin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/udiImage/bin
ENV PCP_DIR=/opt/rh/devtoolset-7/root
ENV PERL5LIB=/opt/rh/devtoolset-7/root//usr/lib64/perl5/vendor_perl:/opt/rh/devtoolset-7/root/usr/lib/perl5:/opt/rh/devtoolset-7/root//usr/share/perl5/vendor_perl
ENV PMI_MMAP_SYNC_WAIT_TIME=600
ENV HOME=/tmp
ENV PYTHONPATH=/lcls2/install/lib/python3.6/site-packages
#
##ENV http_proxy ""
##ENV https_proxy ""
##ENV ftp_proxy ""
#