FROM slaclcls/ana:4.0.17

RUN apt-get update &&\
    apt-get --yes install cmake git && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /img && \
    cd /img && \
    git clone https://github.com/duaneloh/Dragonfly.git && \
    cd Dragonfly && \
    mkdir build && cd build && cmake .. && make install
